const errorResponse = {
  ALREADY_EXIST: "Record already exist",
  NOT_FOUND: "User not found",
  SOME_MISTAKE: "Some mistake",
  UNAUTHORISED: "Unauthorised",
  MISSING_CREDENTIALS: "Missing Credentials",
  SIGNUP_ADMIN: "Cannot sign up as an admin",
  SOMETHING_WRONG: "Something went wrong!",
  UNKNOWN_TYPE: "Unknown type.",
  NOTHING_TO_UPDATE: "There is nothing to update",
  BAD_REQUEST: "Bad Request.",
  INTERNAL_SERVER_ERROR: "Internal Server Error.",
  USER_DOESNT_EXIST: "User doesnt exist",
  FORBIDDEN: "Your are forbidden to perform this action.",
  REQUIRED_FIELD_EMPTY: "Require fields cant be empty",
  INVALID_TOKEN: "Invalid token",
  NO_TOKEN: "No token Provided",
  RECORD_NOEXIST: "No Records found",
  NOT_VALID: "Not valid",
  NOT_REGISTER: "User Not Register",
  USER_ALREADY_REGISTER: "User already registered",
  NOT_VERIFIED: "Otp Not verified",
  TIME_EXPIRE: "Otp expired! Please try again",
  IS_INVALID_OTP: "Invalid otp! Please try again",
  IS_MAX_ATTEMP:
    "You have reached max number of attempts! Please try after sometime",
  IS_USER_NOT_EXIST:
    "The entered number, is not a registered mobile number. Please Sign-Up in the application to proceed further.",
  IS_USER_EXIST: "User already registered!",
  IS_REGISTRATION_NUMBER_EXIST: "This registration_number is already taken",
  FILE_NOT_SELECTED: "File not selected",
  INVALID_PAGE: "Page no should be greater than 0",
  USERNAME_INVALID: "Username is invalid",
  MOBILE_NUMBER_INVALID: "Mobile number is invalid",
  PASSWORD_INVALID: "Password is invalid",
  KYC_FAILURE: "Kyc not verified",
  PLAN_EXIST_FOR_CITY: "Plan already exist for this city",
  LOCATION_ALREADY_ASSIGNED: "Location is already assigned",
  IS_USER_BLOCK: "User Blocked! Please contact to adminstrator",
  FILE_SIZE_EXCEEDED: "File size should not be more than 5 mb",
  INVENTORY_FILE_SIZE_EXCEEDED: "File size should not be more than 10 mb",
  IS_USER_DELETED: "Your account is deleted!! Please try to create an account again.",
  USER_INACTIVE_OLD: "User InActive! Please contact to adminstrator",
  USER_INACTIVE: "User already registered! Please go to login",
  SESSION_EXPIRED : "Login Session expired. Please login again",
  INVALID_TOKEN: "Invalid Token",
  NO_ACCESS: "Access denied"
};
const UserMessage = {
  UPDATE_USER: "updated successfully a user with id",
  DELETE_USER: "deleted successfully a user with userId",
  USERNAME_REQ: "username required",
  PASSWORD_REQ: "Password required",
  USERNAME_LENGTH: "UserName not greater than 30 char",
  PASSWORD_LEANGTH: "password not greater than 15 char",
  FIRST_NAME_REQ: "First Name is required",
  LAST_NAME_REQ: "Last Name is required",
  EMAIL_ID_REQ: "Email id is required",
  EMAIL_ID_VALID: "Email id is Invalid",
  MOBILE_NO_REQ: "Moblie No is required",
  MOBILE_NO_VALID: "Mobile Number Must be Number",
  PASSWORD_NO_VALID:
    "Please enter a password at least 8 character and contain At least one uppercase.At least one lower case.At least one special character. ",
  OTP_REQ: "Otp is required",
  GENDER_REQ: "Gender  is required",
  EMERGENCY_NO_REQ: "Emergency number is required.",
  EMERGENCY_NO_VALID: "Emergency number must be a number.",
  EMERGENCY_NAME_REQ: "Emergency contact name is required.",
  RELATION_REQ: "Relation is required."
};
const CrudMessage = {
  ADD_SUCCESS: "Record added successfully",
  RECORD_FETCH: "Record fetch successfully",
  RIDE_EXTEND: "Ride Extended successfully",
  RECORD_NOT_FETCH: "Record does not exist",
  UPDATE_SUCCESS: "Updated successfully",
  UPDATE_FAILURE: "Update failed",
  DELETE_SUCCESS: "Deleted successfully",
  VERIFY_SUCCESS: "Verify successfully",
  INVOICE_GENRATE: "SMS linc sent successfully",
  VEHICLE_CHANGED: "Vehicle Changed successfully",
  UN_VERIFY_SUCCESS : "Unverified successfully"
};
const successMessages = {
  LOGIN_SUCCESS: "You are logged in Successfully",
  LOGOUT_SUCCESS: "You are logged out Successfully",
  SIGNUP_SUCCESS: "You have been registered sucessfully on Freedo",
  NOTHING_TO_UPDATE: "There is nothing to update",
  UPDATE_SUCCESS: "Data has been successfully update",
  USER_DELETE_SUCCESS: "User has been deleted Successfully.",
  SERVER_START: "Express server listening on port",
  RECORD_FETCH: "record fetch successfully",
  USER_PROFILE: "user profile get successfully",
  KYC_SUCCESS: "KYC verified successfully",
  OTP_SEND: "Otp sent successfully",
  OTP_VERIFY: "Otp verified",
  BOOKING_CONFIRMATION: "your Ride booked confirmed",
  ADDITIONAL_CHARGE_PAID_SUCCESS: "Additional charges paid successfully",
  TRANSACTION_FAILED: "Your transaction has been failed",
  TOKEN_SUCCESS: "Token Generated",
  BLOCK_SUCCESS: "Blocked successfully",
  NOTHING_TO_UPDATE: "There is nothing to update",
  GET_RELATIONS: "Relations get successfully",
};
const ServerStatusCode = {
  NOT_EXIST_CODE: 403,
  NOT_VALID_CODE: 401,
  SUCCESS_CODE: 200,
  EMPTY_CHANGESET:212,
  SERVER_ERROR: 500,
  RECORD_NOTEXIST: 502,
  INVALID_CRED: 403,
  BAD_REQUEST: 400,
  PRECONDION_FAILED: 412,
  UNPROCESSABLE: 422,
  200: "OK",
  201: "Created",
  202: "Accepted",
  204: "No Content",
  212: "No Data found",
  304: "Not Modified",
  305: "Use Proxy",
  307: "Temporary Redirect",
  400: "Bad Request",
  401: "Unauthorized",
  402: "Payment Required",
  403: "Forbidden",
  404: "Not Found",
  407: "Proxy Authentication Required",
  408: "Request Time-out",
  413: "Request Entity Too Large",
  500: "Internal Server Error",
  TOKEN_ERROR: "Invalid Token",
};
module.exports = {
  errorResponse,
  successMessages,
  ServerStatusCode,
  UserMessage,
  CrudMessage
};
